---
- name: Deploy Monasca Agent
  hosts: localhost
  become: yes
  roles:
  - role: stackhpc.monasca-agent
    keystone_url: "http://{{ aio_vip_address }}:5000/v3"
    monasca_user: root
    monasca_agent_user: os-monasca-agent
    monasca_agent_password: "os-password"
    monasca_agent_project: openstack
    monasca_agent_branch: stable/ussuri
    monasca_pip_extra_args: "-c https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?h=stable/ussuri"
    monasca_endpoint_type: public
    monasca_project_domain_name: Default
    monasca_user_domain_name: Default
    monasca_region_name: RegionOne
    monasca_service_type: monitoring
    monasca_agent_system_only: true
    monasca_agent_custom_plugin_repos:
    - "https://github.com/stackhpc/stackhpc-monasca-agent-plugins.git"
    monasca_log_level: INFO
